flash用到的文件列表：
1)delrec.asp
2)expquery.asp
3)loadrec.asp
4)saverec.asp
5)stmodify.asp
6)studel.asp
7)stulgout.asp
8)stulogin.asp
9)stureg.asp
10)studb.mdb
11)yiqidb.mdb

说明如下：
注意：所有asp页面只接受POST方式发送的数据。
1）删除yiqidb.mdb里面的仪器记录，以学号（xuehao）和文件名（name）为参数，删除数据库中所有该学号（xuehao）的该文件名（name）的记录。若文件名对应的记录存在则返回：error=0；否则返回error=71。
2）查询studb.mdb里面的学生登录记录，以学号（xuehao）、姓名（xingming）和密码（mima）为参数。若没有记录（比如被管理员删除）则返回：error=52；若姓名与学号不符则返回：error=51；若密码错误，则返回：error=53；否则就成功并返回：error=0&query=记录字符串。（该字符串以字符p为换行标志，以字符t为记录列标志。）
3）载入yiqidb.mdb里保存的仪器时用，当只以学号（xuehao）为参数时，返回：error=0&yqnamelist=记录的所有文件名的字符串&yqnumber=记录数。（该字符串中包含该学号的所有记录的名字，记录数为记录的总数。）当以学号（xuehao）和文件名（name）为参数时，返回：error=0&yqstring=该记录的所有仪器记录的字符串，以字符:为分隔符。记录不存在则返回error=61。
4）保存当前实验的所有仪器状态到yiqidb.mdb，以仪器总数（total），学号（xuehao）、文件名（name）和仪器状态字符串（yqstring）为参数。若已存在对应记录，返回：error=51；否则返回：error=0。
5）修改studb.mdb里的学生注册信息，以学号（xuehao）、姓名（xingming）、原密码（yuanmima）、密码（mima）、Email（email）和qq号（qq）为参数，修改对应学号的注册信息。若后三者为空则不修改后三者。不存在该学生则返回：error=40。若原密码为空则返回已注册信息，以使学生在修改时能看到已注册的信息；若姓名不符则返回：error=42；若原密码不符则返回：error=41；若成功则返回：error=0。
6）删除studb.mdb里的学生所有记录，以学号（xuehao）和密码（password）为参数。该文件主要由管理员访问，以删除对应学号的所有记录。密码设在该文件中的一个if中，由管理员负责。成功将返回：error=0；学号不存在返回：error=1。
7）记录学生的注销时间到studb.mdb中，以学号（xuehao）、次数（counter）和成绩（score）为参数，将当前时间和此次注销的成绩（score）添加到对应学号的此次登录记录中。此次记录不存在（应该不至于）则返回：error=30；成功则返回：error=0。
8）记录学生的登录时间到studb.mdb中，并判断提供信息能否登录，以学号（xuehao）、姓名（xingming）和密码（mima）为参数。若该学号不存在则返回：error=22；若姓名与学号不符则返回：error=21；若密码部队则返回：error=23；若成功则返回：error=0&counter=次数。（次数为当前是第几次登录。）
9）注册新学号到studb.mdb中，以学号（xuehao）、姓名（xingming）、密码（mima）、Email（email）和qq号（qq）为参数。若该学号存在则返回：error=10；否则返回：error=0。
10）学生记录。包括两个表：students和stuexp。students表的字段包括：xuehao、xingming、mima、email、qq和counter，主键为xuehao；stuexp表的字段包括：xuehao、counter、logintime、logouttime和score，主键为xuehao。
11）仪器记录。仅yiqi表，字段包括：xuehao、name、category、temperature、x、y、rotation、xscale、i和curtime，无主键。
